apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cert-cluster-issuer
    meta.helm.sh/release-name: n8n
    meta.helm.sh/release-namespace: n8n
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: n8n-ingress
  namespace: n8n
spec:
  ingressClassName: nginx
  rules: 
  - host: n8n.cbxon.co.uk
    http:
      paths:
      - backend:
          service:
            name: n8n
            port:
              number: 5678
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - n8n.cbxon.co.uk
    secretName: certificate-n8n