services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: media_gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file: wireguard.env
    ports:
      - 9191:9191
    networks:
      - caddy_net

  dispatcharr:
    image: ghcr.io/dispatcharr/dispatcharr:latest
    container_name: dispatcharr
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - 992   
    environment:
      - DISPATCHARR_ENV=aio
      - REDIS_HOST=localhost
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - DISPATCHARR_LOG_LEVEL=info
    volumes:
      - dispatcharr_data:/data
      - /data/backups/dispatcharr:/data/backups
    network_mode: "service:gluetun"

  jellyfin:
    image: docker.io/jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - 992   
    environment:
      - JELLYFIN_PublishedServerUrl=http://jellyfin.cbxon.co.uk
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - /data/tv:/tv:ro
      - /data/movies:/movies:ro
    ports:
      - 8096:8096
    networks:
      - caddy_net

volumes:
  dispatcharr_data:
  jellyfin_config:
  jellyfin_cache:

networks:
  caddy_net:
    name: infra_caddy_net
    external: true
