apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: default
spec:
  install:
    createNamespace: true
  targetNamespace: kube-prometheus-stack
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "77.5.0"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: default
      interval: 10m
  values:
    grafana:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "cert-cluster-issuer"
          nginx.ingress.kubernetes.io/rewrite-target: /
        hosts:
          - grafana.cbxon.co.uk
        tls:
        - secretName: certificate-monitoring
          hosts:
            - grafana.cbxon.co.uk