---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: infra-controllers
resources:
  - cert-manager.yaml
  - ingress-nginx.yaml
  - external-dns.yaml
  - external-secrets.yaml
  - longhorn.yaml