---
- name: Configure dependencies
  hosts: core
  tasks:
    - name: Install required packages
      become: true
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present
        update_cache: true

    - name: Ensure apt keyrings directory exists
      become: true
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Docker GPG key
      become: true
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add Docker apt source
      become: true
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/docker.sources
        mode: "0644"
        content: |
          Types: deb
          URIs: https://download.docker.com/linux/ubuntu
          Suites: {{ ansible_distribution_release }}
          Components: stable
          Signed-By: /etc/apt/keyrings/docker.asc

    - name: Install Docker
      become: true
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /opt/docker

- name: Deploy Ingest stack
  hosts: core
  become: true
  tasks:
    - name: Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /opt/docker/ingest

    - name: Copy Docker Files to target
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0644"
      loop:
        - src: files/ingest-docker-compose.yaml
          dest: /opt/docker/ingest/docker-compose.yml
        - src: files/wireguard.env
          dest: /opt/docker/ingest/wireguard.env
          
    - name: Deploy Download stack
      community.docker.docker_compose_v2:
        project_src: /opt/docker/ingest
        files:
          - docker-compose.yml
        state: present

- name: Deploy Media stack
  hosts: core
  become: true
  tasks:
    - name: Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /opt/docker/media

    - name: Copy Docker Files to target
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0644"
      loop:
        - src: files/media-docker-compose.yaml
          dest: /opt/docker/media/docker-compose.yml
        - src: files/wireguard.env
          dest: /opt/docker/media/wireguard.env
          
    - name: Deploy Download stack
      community.docker.docker_compose_v2:
        project_src: /opt/docker/media
        files:
          - docker-compose.yml
        state: present

- name: Deploy Infra stack
  hosts: core
  become: true
  tasks:
    - name: Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /opt/docker/infra

    - name: Copy Docker Files to target
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0644"
      loop:
        - src: files/infra-docker-compose.yaml
          dest: /opt/docker/ingest/docker-compose.yml
          
    - name: Deploy Download stack
      community.docker.docker_compose_v2:
        project_src: /opt/docker/infra
        files:
          - docker-compose.yml
        state: present
