apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-api-key
  namespace: cert-manager
spec:
  schedule: "*/30 * * * *"          # every 30 mins
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          serviceAccountName: secret-grabber
          restartPolicy: OnFailure
          containers:
          - name: secret-grabber
            image: bitnami/kubectl
            command:
              - /bin/sh
              - -c
              - |
                set -e

                APIKEY=$(kubectl get secrets cloudflare-api-key -n external-dns -ojsonpath='{.data.apiKey}')
                if ! kubectl get secret cloudflare-api-key -n cert-manager >/dev/null 2>&1; then
                  kubectl create secret generic cloudflare-api-key -n cert-manager --from-literal=apiKey="$(echo -n $APIKEY)"
                else
                  kubectl patch secret cloudflare-api-key -n cert-manager --type=merge -p "{\"data\":{\"apiKey\":\"$(echo -n $APIKEY)\"}}"
                fi