apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-grabber
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-grabber-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "patch", "update"]
  resourceNames: ["cloudflare-api-key"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-grabber-binding
subjects:
- kind: ServiceAccount
  name: secret-grabber
  namespace: cert-manager
roleRef:
  kind: ClusterRole
  name: secret-grabber-role
  apiGroup: rbac.authorization.k8s.io