apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomizations
resources:
  - namespace.yaml
  - elasticsearch-pv.yaml
  - elasticsearch.yaml
  - elasticsearch-autoscaler.yaml
  - kibana.yaml
  - kibana-ingress.yaml
